# Generated by Django 4.1.3 on 2022-12-18 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
            preserve_default=False,
        ),
    ]
