# Generated by Django 4.1.3 on 2022-12-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='cuerpo',
        ),
    ]
